"""add_saved_assets

Revision ID: 06a5869099ac
Revises: 72f84daffc8e
Create Date: 2026-05-11 21:14:18.958790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06a5869099ac'
down_revision: Union[str, Sequence[str], None] = '72f84daffc8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('elements_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_assets_id'), 'saved_assets', ['id'], unique=False)
    op.create_index(op.f('ix_saved_assets_user_id'), 'saved_assets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_assets_user_id'), table_name='saved_assets')
    op.drop_index(op.f('ix_saved_assets_id'), table_name='saved_assets')
    op.drop_table('saved_assets')
    # ### end Alembic commands ###
