"""remove active_workspace_id from users

Revision ID: 453de1d21145
Revises: 7282545cf8bb
Create Date: 2026-08-16 13:28:00.472876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453de1d21145'
down_revision: Union[str, Sequence[str], None] = '7282545cf8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_active_workspace_id'), table_name='users')
    op.drop_constraint(op.f('users_active_workspace_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'active_workspace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_workspace_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_active_workspace_id_fkey'), 'users', 'workspaces', ['active_workspace_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_users_active_workspace_id'), 'users', ['active_workspace_id'], unique=False)
    # ### end Alembic commands ###
