"""dodana kolumna invited_id

Revision ID: 5761220c6251
Revises: 7db6d9ac37e6
Create Date: 2025-11-15 11:25:14.114243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5761220c6251'
down_revision: Union[str, Sequence[str], None] = '7db6d9ac37e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_invites', sa.Column('invited_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workspace_invites', 'users', ['invited_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_invites', type_='foreignkey')
    op.drop_column('workspace_invites', 'invited_id')
    # ### end Alembic commands ###
