"""remove verification_code from users

Revision ID: 7282545cf8bb
Revises: a3f7c9d1e8b2
Create Date: 2026-07-27 18:25:46.790364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7282545cf8bb'
down_revision: Union[str, Sequence[str], None] = 'a3f7c9d1e8b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_code_expires')
    op.drop_column('users', 'verification_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('verification_code_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
