"""Add active_workspace_id to users

Revision ID: 7db6d9ac37e6
Revises: de74c1c104a3
Create Date: 2025-11-12 23:03:38.569212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db6d9ac37e6'
down_revision: Union[str, Sequence[str], None] = 'de74c1c104a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_active_workspace_id'), 'users', ['active_workspace_id'], unique=False)
    op.create_foreign_key(None, 'users', 'workspaces', ['active_workspace_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_active_workspace_id'), table_name='users')
    op.drop_column('users', 'active_workspace_id')
    # ### end Alembic commands ###
