"""dodana kolumna created_at

Revision ID: 8647bf7f8acd
Revises: a480c8e5ce34
Create Date: 2025-11-08 13:06:10.148438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8647bf7f8acd'
down_revision: Union[str, Sequence[str], None] = 'a480c8e5ce34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('workspaces', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'created_at')
    op.drop_column('boards', 'created_at')
    # ### end Alembic commands ###
