"""naprawa relation w WorkspaceInvites

Revision ID: 8cb110d44501
Revises: 5761220c6251
Create Date: 2025-11-15 12:41:42.339546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb110d44501'
down_revision: Union[str, Sequence[str], None] = '5761220c6251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workspace_invites_invited_id'), 'workspace_invites', ['invited_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_invites_invited_id'), table_name='workspace_invites')
    # ### end Alembic commands ###
