"""drop board_elements table

Revision ID: d315e28cb69c
Revises: 0059c60824f3
Create Date: 2026-09-22 17:52:07.551602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd315e28cb69c'
down_revision: Union[str, Sequence[str], None] = '0059c60824f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_elements_board_id'), table_name='board_elements')
    op.drop_index(op.f('ix_board_elements_created_at'), table_name='board_elements')
    op.drop_index(op.f('ix_board_elements_element_id'), table_name='board_elements')
    op.drop_index(op.f('ix_board_elements_id'), table_name='board_elements')
    op.drop_index(op.f('ix_board_elements_is_deleted'), table_name='board_elements')
    op.drop_table('board_elements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_elements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('element_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('board_elements_board_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('board_elements_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('board_elements_pkey'))
    )
    op.create_index(op.f('ix_board_elements_is_deleted'), 'board_elements', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_board_elements_id'), 'board_elements', ['id'], unique=False)
    op.create_index(op.f('ix_board_elements_element_id'), 'board_elements', ['element_id'], unique=False)
    op.create_index(op.f('ix_board_elements_created_at'), 'board_elements', ['created_at'], unique=False)
    op.create_index(op.f('ix_board_elements_board_id'), 'board_elements', ['board_id'], unique=False)
    # ### end Alembic commands ###
