"""add workspace share links table

Revision ID: d609c987c1eb
Revises: 453de1d21145
Create Date: 2026-08-24 16:23:53.838303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd609c987c1eb'
down_revision: Union[str, Sequence[str], None] = '453de1d21145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workspace_share_links_active_target', 'workspace_share_links', ['workspace_id', 'board_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index(op.f('ix_workspace_share_links_board_id'), 'workspace_share_links', ['board_id'], unique=False)
    op.create_index(op.f('ix_workspace_share_links_id'), 'workspace_share_links', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_share_links_token'), 'workspace_share_links', ['token'], unique=True)
    op.create_index(op.f('ix_workspace_share_links_workspace_id'), 'workspace_share_links', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_share_links_workspace_id'), table_name='workspace_share_links')
    op.drop_index(op.f('ix_workspace_share_links_token'), table_name='workspace_share_links')
    op.drop_index(op.f('ix_workspace_share_links_id'), table_name='workspace_share_links')
    op.drop_index(op.f('ix_workspace_share_links_board_id'), table_name='workspace_share_links')
    op.drop_index('ix_workspace_share_links_active_target', table_name='workspace_share_links', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('workspace_share_links')
    # ### end Alembic commands ###
