"""Drop is_online from boards_users table

Revision ID: df88d216fb68
Revises: d609c987c1eb
Create Date: 2026-09-01 17:42:52.368976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df88d216fb68'
down_revision: Union[str, Sequence[str], None] = 'd609c987c1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_users_is_online'), table_name='board_users')
    op.drop_column('board_users', 'is_online')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_users', sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_board_users_is_online'), 'board_users', ['is_online'], unique=False)
    # ### end Alembic commands ###
