"""Add avatar_url column to users

Revision ID: ed744dfc7170
Revises: 67531be2d2f7
Create Date: 2026-04-16 18:14:27.078301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed744dfc7170'
down_revision: Union[str, Sequence[str], None] = '67531be2d2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_boards_last_modified_by'), 'boards', ['last_modified_by'], unique=False)
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_workspace_invites_invited_by'), 'workspace_invites', ['invited_by'], unique=False)
    op.create_index(op.f('ix_workspace_invites_workspace_id'), 'workspace_invites', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_invites_workspace_id'), table_name='workspace_invites')
    op.drop_index(op.f('ix_workspace_invites_invited_by'), table_name='workspace_invites')
    op.drop_column('users', 'avatar_url')
    op.drop_index(op.f('ix_boards_last_modified_by'), table_name='boards')
    # ### end Alembic commands ###
